name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations and tests
      env:
        SECRET_KEY: test-secret
        DEBUG: 'True'
        ALLOWED_HOSTS: 127.0.0.1,localhost
      run: |
        python manage.py migrate
        python manage.py test